### ISSUE TITLE
undef not found when used with requirejs 2.1.4

### ISSUE THREAD

**Issue by jackysee** [iammerrick/Squire.js#19]
I try to run the tests with requirejs 2.1.4. The `clean` method has error.

```
clean
should not mock the requested module
TypeError: Object #<Object> has no method 'undef'
    at Squire.clean (file:///D:/workspace/web/Squire.js/src/Squire.js:134:37)
    at Context.<anonymous> (file:///D:/workspace/web/Squire.js/test/tests/SquireTests.js:262:12)
    at Test.Runnable.run (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3471:15)
    at Runner.runTest (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3796:10)
    at file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3842:12
    at next (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3724:14)
    at file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3733:7
    at next (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3681:23)
    at file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3701:5
    at process.removeListener.window.onerror (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:4621:44)
```

**Comment by jackysee** [comment]
I tried to replace those `undef` line to use `this.load`

```
      //requirejs.s.contexts[this.id].undef(mock);
      this.load.undef(mock);
```

The clean up tests run fine. But the 'shared squire' tests seems do not pass:

```
should allow me to mock after a clean
Error: the string "Uncaught expected 'Red' to equal 'Dragon Print'" was thrown, throw an Error :)
    at Runner.fail (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3641:11)
    at Runner.uncaught (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3915:8)
    at uncaught (file:///D:/workspace/web/Squire.js/test/vendor/mocha.js:3945:10)
```

**Comment by jackysee** [comment]
All the test cases passes for 2.1.4 if I add the following line:

```
    for (path in this.mocks) {
      // Require.js code to the next require.
      this.load.undef(path);
      define(path, this.mocks[path]);
    }
```

but the test cases would fail in the requirejs 2.0.6.

**Comment by iammerrick** [comment]
@jrburke It looks like undef was removed from require.js contexts?

**Comment by iammerrick** [comment]
@jackysee Thanks a bunch for reporting this. I've resolve this problem with the following commit: https://github.com/iammerrick/Squire.js/commit/b998b7bb9172b4350311df847a9f90abf7095b48#L1R57 Please re-download and let me know if it works!
