### ISSUE TITLE
Squire: requirejs is not defined

### ISSUE THREAD

**Issue by micheledisalvatore** [iammerrick/Squire.js#69]
Hi. I'm trying to use squire with Mocha and Gulp on a front end project.

``` javascript
var chai = require('chai')
  , requirejs = require("requirejs")
  , assert = require("assert")
  , should = require("should")
  , define = require('amdefine/intercept')
  ;

requirejs.config({
  baseUrl: 'components',
  nodeRequire: require
});

var Squire = requirejs("squirejs");

describe('Test', function() {
  var injector = new Squire()
    , Service
    ;

  injector
    .mock('foo', {
      foo : function() {
        return "foofoo"; /* instead of just foo */
      }
    });

  beforeEach(function(done) {

    injector.require(["service"], function(service) {
        Service = service;
        done();
      });
  });

  it('Should be 2.', function() {
    console.log('it');
  });

});
```

but I catch this error in Squire module:

``` bash
ReferenceError: requirejs is not defined
    at getContext (node_modules/squirejs/src/Squire.js:58:12)
    at Squire.configure (node_modules/squirejs/src/Squire.js:107:15)
    at new Squire (node_modules/squirejs/src/Squire.js:82:20)
    at Suite.<anonymous> (service.test.js:18:18)
    at context.describe.context.context (node_modules/gulp-mocha/node_modules/mocha/lib/interfaces/bdd.js:49:10)
    at Object.<anonymous> (service.test.js:16:1)
```

Where is my mistake?

I've found also this [gist](https://gist.github.com/mukeshsoni/2b507ff1eacda5cd710a), but it looks equal to mine.

**Comment by micheledisalvatore** [comment]
Ok I've fixed. I was missing the packages property in the requirejs.config.

``` javascript
var chai = require('chai')
  , requirejs = require("requirejs")
  , should = chai.should()
  ;

requirejs.config({
  baseUrl: '.',
  nodeRequire: require,
  packages: [
    {
      name: "squirejs",
      location: "node_modules/squirejs",
      main: "src/Squire"
    }
  ]
});

var Squire = requirejs("squirejs");

describe('Test', function() {
  var injector = new Squire()
    , Service
    ;

  injector
    .mock('foo', {
      foo : function() {
        return "foofoo"; /* instead of just foo */
      }
    });

  beforeEach(function(done) {

    injector.require(["service"], function(service) {
        Service = service;
        done();
      });
  });

  it('Should be 2.', function() {
    console.log('it');
  });

});
```
